import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Suspense } from "react";
import { NavBar } from "~/components/nav-bar";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Suspense fallback={<div>Loading...</div>}>
			<ClerkProvider dynamic>
				<html lang="en">
					<body className={`${geist.variable} antialiased`}>
						<TRPCReactProvider>
							<div className="min-h-screen">
								<NavBar />

								{children}
							</div>
						</TRPCReactProvider>
					</body>
				</html>
			</ClerkProvider>
		</Suspense>
	);
}
