import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Suspense } from "react";
import { NavBar } from "~/components/nav-bar";
import { TRPCReactProvider } from "~/trpc/react";
import { AudioPlayerProvider } from "~/contexts/audio-player-context";
import { Toaster } from "~/components/ui/sonner";
import { AudioPlayer } from "~/components/audio-player";
import { PodcastChat } from "~/components/chat";
import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Suspense fallback={<div>Loading...</div>}>
			<ClerkProvider dynamic>
				<html lang="en">
					<body className={`${geist.variable} antialiased`}>
						<TRPCReactProvider>
							<NuqsAdapter>
								<AudioPlayerProvider>
									<div className="min-h-screen pb-36">
										<NavBar />

										{children}
									</div>

									<Toaster position="top-center" />

									<PodcastChat />

									<AudioPlayer />
								</AudioPlayerProvider>
							</NuqsAdapter>
						</TRPCReactProvider>
					</body>
				</html>
			</ClerkProvider>
		</Suspense>
	);
}
